export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  DIAGNOSE: "/diagnose",
  HISTORY: "/history",
  PROFILE: "/profile",
  RESULT: "/result",
  ADMIN_DASHBOARD: "/admin",
  ADMIN_USERS: "/admin/users",
  ADMIN_DISEASES: "/admin/diseases",
  ADMIN_DOCUMENTS: "/admin/documents",
  ADMIN_MODELS: "/admin/models",
  ADMIN_FEEDBACK: "/admin/feedback",
  ADMIN_CONFIGS: "/admin/configs",
  ADMIN_KNOWLEDGE: "/admin/knowledge",
} as const;
