export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  VERIFY_OTP: "/verify-otp",
  DIAGNOSE: "/diagnose",
  HISTORY: "/history",
  FORUM: "/forum",
  PROFILE: "/profile",
  RESULT: "/result",
  ONBOARDING_LOCATION: "/onboarding/location",
  ONBOARDING_PASSWORD: "/onboarding/password",
  ADMIN_DASHBOARD: "/admin",
  ADMIN_USERS: "/admin/users",
  ADMIN_DISEASES: "/admin/diseases",
  ADMIN_DOCUMENTS: "/admin/documents",
  ADMIN_MODELS: "/admin/models",
  ADMIN_FEEDBACK: "/admin/feedback",
  ADMIN_CONFIGS: "/admin/configs",
  ADMIN_KNOWLEDGE: "/admin/knowledge",
  ADMIN_FORUM: "/admin/forum",
} as const;
